[build]
  publish = "dist"
  command = "npm run build"

# Redirect API calls to your JSON server
[[redirects]]
  from = "/users"
  to = "https://my-json-server.typicode.com/Infinity2209/userAndProductManagement/users"
  status = 302

[[redirects]]
  from = "/users/*"
  to = "https://my-json-server.typicode.com/Infinity2209/userAndProductManagement/users/:splat"
  status = 302

[[redirects]]
  from = "/products"
  to = "https://my-json-server.typicode.com/Infinity2209/userAndProductManagement/products"
  status = 302

[[redirects]]
  from = "/products/*"
  to = "https://my-json-server.typicode.com/Infinity2209/userAndProductManagement/products/:splat"
  status = 302

[build.environment]
  NODE_VERSION = "18"
